on:
  # Schedule updates (each day)
  schedule: [{cron: "0 12 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/metrics.yml'
jobs:
  language-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SichangHe
          template: classic
          base: ''
          config_timezone: Asia/Hong_Kong
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 20
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size
          plugin_languages_ignored: Batchfile, CSS, Handlebars, HTML, Jupyter Notebook, Less, Tex, VBScript, Markdown
          plugin_languages_limit: 10
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: STATS401, learn_program, Notes_Steven, mdbook_katex_template, igem-2022-dku-backup, mdbook_fancy_theme, BigDecimal-Matrix-and-column-vector-calculator-in-Java
